"""add embeddings column with server default

Revision ID: 0724098f2d79
Revises: 2cfae3938d63
Create Date: 2025-12-03 10:08:06.156818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0724098f2d79'
down_revision: Union[str, Sequence[str], None] = '2cfae3938d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('embeddings_status', sa.String(length=30), server_default='pending', nullable=False))
    op.create_index(op.f('ix_chats_embeddings_status'), 'chats', ['embeddings_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_embeddings_status'), table_name='chats')
    op.drop_column('chats', 'embeddings_status')
    # ### end Alembic commands ###
