"""add conversation history table

Revision ID: 293bf8cae101
Revises: 3bdda54c971f
Create Date: 2025-11-18 02:56:39.769901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293bf8cae101'
down_revision: Union[str, Sequence[str], None] = '3bdda54c971f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_history_chat_id'), 'conversation_history', ['chat_id'], unique=False)
    # op.drop_index(op.f('embeddings_chat_id_idx'), table_name='embeddings')
    # op.drop_index(op.f('embeddings_chat_source_idx'), table_name='embeddings')
    # op.drop_index(op.f('embeddings_embedding_ivfflat'), table_name='embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # op.create_index(op.f('ix_embeddings_chat_id'), 'embeddings', ['chat_id'], unique=False)
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_embeddings_chat_id'), table_name='embeddings')
    # op.create_index(op.f('embeddings_embedding_ivfflat'), 'embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # op.create_index(op.f('embeddings_chat_source_idx'), 'embeddings', ['chat_id', 'source_table', 'source_id'], unique=False)
    # op.create_index(op.f('embeddings_chat_id_idx'), 'embeddings', ['chat_id'], unique=False)
    # op.drop_index(op.f('ix_conversation_history_chat_id'), table_name='conversation_history')
    op.drop_table('conversation_history')
    # ### end Alembic commands ###
