"""Version 9

Revision ID: 2bae362756b9
Revises: 50eb9bd827e5
Create Date: 2025-11-01 08:15:21.483742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bae362756b9'
down_revision: Union[str, Sequence[str], None] = '50eb9bd827e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chats_created_at'), 'chats', ['created_at'], unique=False)
    op.create_index(op.f('ix_chats_sentiment_status'), 'chats', ['sentiment_status'], unique=False)
    op.create_index(op.f('ix_message_sentiments_analysis_timestamp'), 'message_sentiments', ['analysis_timestamp'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_participant_id'), 'messages', ['participant_id'], unique=False)
    op.drop_constraint(op.f('messages_participant_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'participants', ['participant_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_participants_chat_id'), 'participants', ['chat_id'], unique=False)
    op.create_index(op.f('ix_participants_created_at'), 'participants', ['created_at'], unique=False)
    op.create_index(op.f('ix_segment_sentiments_analysis_timestamp'), 'segment_sentiments', ['analysis_timestamp'], unique=False)
    op.create_index(op.f('ix_segments_sender_sender_id'), 'segments_sender', ['sender_id'], unique=False)
    op.create_index(op.f('ix_segments_sender_time_segment_id'), 'segments_sender', ['time_segment_id'], unique=False)
    op.create_index(op.f('ix_segments_time_chat_id'), 'segments_time', ['chat_id'], unique=False)
    op.create_index(op.f('ix_segments_time_start_time'), 'segments_time', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_time_start_time'), table_name='segments_time')
    op.drop_index(op.f('ix_segments_time_chat_id'), table_name='segments_time')
    op.drop_index(op.f('ix_segments_sender_time_segment_id'), table_name='segments_sender')
    op.drop_index(op.f('ix_segments_sender_sender_id'), table_name='segments_sender')
    op.drop_index(op.f('ix_segment_sentiments_analysis_timestamp'), table_name='segment_sentiments')
    op.drop_index(op.f('ix_participants_created_at'), table_name='participants')
    op.drop_index(op.f('ix_participants_chat_id'), table_name='participants')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_participant_id_fkey'), 'messages', 'participants', ['participant_id'], ['id'])
    op.drop_index(op.f('ix_messages_participant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index(op.f('ix_message_sentiments_analysis_timestamp'), table_name='message_sentiments')
    op.drop_index(op.f('ix_chats_sentiment_status'), table_name='chats')
    op.drop_index(op.f('ix_chats_created_at'), table_name='chats')
    # ### end Alembic commands ###
