"""update_embedding_dimension_to_3072

Revision ID: 3bdda54c971f
Revises: e817f10d0cc8
Create Date: 2025-11-12 14:58:09.216085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bdda54c971f'
down_revision: Union[str, Sequence[str], None] = 'e817f10d0cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto-generated by Alembic - manually adjusted ###
    print("Altering embedding column type to vector(3072)...")
    
    # This command changes the database column to accept the new dimension.
    op.execute("ALTER TABLE public.embeddings ALTER COLUMN embedding TYPE vector(1536);")
    
    print("Done.")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - manually adjusted ###
    print("Reverting embedding column type to vector(1536)...")
    
    # This reverts the change if you ever need to.
    op.execute("ALTER TABLE public.embeddings ALTER COLUMN embedding TYPE vector(1536);")
    
    print("Done.")
    # ### end Alembic commands ###