"""add sources to conversation history

Revision ID: 4de3dfd809bd
Revises: 293bf8cae101
Create Date: 2025-11-19 02:53:46.860280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de3dfd809bd'
down_revision: Union[str, Sequence[str], None] = '293bf8cae101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_history', sa.Column('sources', sa.JSON(), nullable=True))
    # op.drop_index(op.f('embeddings_chat_id_idx'), table_name='embeddings')
    # op.drop_index(op.f('embeddings_chat_source_idx'), table_name='embeddings')
    # op.drop_index(op.f('embeddings_embedding_ivfflat'), table_name='embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # op.create_index(op.f('ix_embeddings_chat_id'), 'embeddings', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_embeddings_chat_id'), table_name='embeddings')
    # op.create_index(op.f('embeddings_embedding_ivfflat'), 'embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # op.create_index(op.f('embeddings_chat_source_idx'), 'embeddings', ['chat_id', 'source_table', 'source_id'], unique=False)
    # op.create_index(op.f('embeddings_chat_id_idx'), 'embeddings', ['chat_id'], unique=False)
    op.drop_column('conversation_history', 'sources')
    # ### end Alembic commands ###
