"""Version 8

Revision ID: 50eb9bd827e5
Revises: bbbad8eb92e1
Create Date: 2025-10-18 02:49:04.517995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50eb9bd827e5'
down_revision: Union[str, Sequence[str], None] = 'bbbad8eb92e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('cancel_requested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'cancel_requested')
    # ### end Alembic commands ###
