"""version 5

Revision ID: 51088f15a504
Revises: 576915939aff
Create Date: 2025-10-12 02:43:12.573367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51088f15a504'
down_revision: Union[str, Sequence[str], None] = '576915939aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('sentiment_status', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'sentiment_status')
    # ### end Alembic commands ###
