"""version 4

Revision ID: 576915939aff
Revises: 9c071425ee4a
Create Date: 2025-10-10 17:57:04.404537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '576915939aff'
down_revision: Union[str, Sequence[str], None] = '9c071425ee4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments_sender',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_segment_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('combined_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_segment_id'], ['segments_time.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_sentiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('overall_label', sa.String(length=50), nullable=False),
    sa.Column('score_positive', sa.Float(), nullable=False),
    sa.Column('score_negative', sa.Float(), nullable=False),
    sa.Column('score_neutral', sa.Float(), nullable=False),
    sa.Column('sentences_summary', sa.JSON(), nullable=True),
    sa.Column('opinions', sa.JSON(), nullable=True),
    sa.Column('api_version', sa.String(length=50), nullable=True),
    sa.Column('analysis_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_sentiments_message_id'), 'message_sentiments', ['message_id'], unique=True)
    op.create_table('segment_sentiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_segment_id', sa.Integer(), nullable=False),
    sa.Column('overall_label', sa.String(length=50), nullable=False),
    sa.Column('score_positive', sa.Float(), nullable=False),
    sa.Column('score_negative', sa.Float(), nullable=False),
    sa.Column('score_neutral', sa.Float(), nullable=False),
    sa.Column('sentences_summary', sa.JSON(), nullable=True),
    sa.Column('opinions', sa.JSON(), nullable=True),
    sa.Column('api_version', sa.String(length=50), nullable=True),
    sa.Column('analysis_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sender_segment_id'], ['segments_sender.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_sentiments_sender_segment_id'), 'segment_sentiments', ['sender_segment_id'], unique=True)
    op.drop_table('sentiments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overall_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score_positive', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('score_negative', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('score_neutral', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sentences_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('opinions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('api_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('analysis_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('error_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('sentiments_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sentiments_pkey')),
    sa.UniqueConstraint('message_id', name=op.f('sentiments_message_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_segment_sentiments_sender_segment_id'), table_name='segment_sentiments')
    op.drop_table('segment_sentiments')
    op.drop_index(op.f('ix_message_sentiments_message_id'), table_name='message_sentiments')
    op.drop_table('message_sentiments')
    op.drop_table('segments_sender')
    op.drop_table('segments_time')
    # ### end Alembic commands ###
