"""Version 7

Revision ID: bbbad8eb92e1
Revises: f8746e269698
Create Date: 2025-10-13 03:43:39.044102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbad8eb92e1'
down_revision: Union[str, Sequence[str], None] = 'f8746e269698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_message_sentiments_overall_label'), 'message_sentiments', ['overall_label'], unique=False)
    op.create_index(op.f('ix_message_sentiments_overall_label_score'), 'message_sentiments', ['overall_label_score'], unique=False)
    op.alter_column('messages', 'raw',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_segment_sentiments_overall_label'), 'segment_sentiments', ['overall_label'], unique=False)
    op.create_index(op.f('ix_segment_sentiments_overall_label_score'), 'segment_sentiments', ['overall_label_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_sentiments_overall_label_score'), table_name='segment_sentiments')
    op.drop_index(op.f('ix_segment_sentiments_overall_label'), table_name='segment_sentiments')
    op.alter_column('messages', 'raw',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_message_sentiments_overall_label_score'), table_name='message_sentiments')
    op.drop_index(op.f('ix_message_sentiments_overall_label'), table_name='message_sentiments')
    # ### end Alembic commands ###
