"""create embeddings table and vector extension

Revision ID: c4f1502f712e
Revises: d77bd9f8ce2f
Create Date: 2025-11-11 04:08:57.649328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f1502f712e'
down_revision: Union[str, Sequence[str], None] = 'd77bd9f8ce2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto-generated by Alembic - manually adjusted ###
    
    # Step 1: Create the vector extension if it doesn't exist 
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    
    # Step 2: Create the embeddings table using the exact DDL [cite: 8-17]
    # Note: We use 1536 for the embedding dimension as specified [cite: 6, 11]
    op.execute("""
        CREATE TABLE public.embeddings (
            id BIGSERIAL PRIMARY KEY,
            chat_id INTEGER NOT NULL,
            source_table TEXT NOT NULL,
            source_id INTEGER NOT NULL,
            embedding vector(1536) NOT NULL,
            text_excerpt TEXT,
            metadata JSONB DEFAULT '{}'::jsonb,
            created_at timestamptz DEFAULT now()
        );
    """)
    
    # Step 3: Add the foreign key constraint to your chats table [cite: 18-20]
    # This enables ON DELETE CASCADE, as requested by your 4-hour TTL design.
    op.execute("""
        ALTER TABLE public.embeddings
        ADD CONSTRAINT fk_embeddings_chats
        FOREIGN KEY (chat_id) REFERENCES public.chats (id) ON DELETE CASCADE;
    """)
    
    # Step 4: Create the standard index for chat_id lookups [cite: 22]
    op.execute("""
        CREATE INDEX embeddings_chat_id_idx ON public.embeddings (chat_id);
    """)
    
    # Step 5: Create the composite index for common lookups [cite: 24]
    op.execute("""
        CREATE INDEX embeddings_chat_source_idx ON public.embeddings (chat_id, source_table, source_id);
    """)
    
    # Step 6: Create the ANN index 
    # Using 'vector_l2_ops' for Euclidean distance, which the guide's
    # query operator '<=>' relies on[cite: 132, 141].
    op.execute("""
        CREATE INDEX embeddings_embedding_ivfflat ON public.embeddings USING ivfflat (embedding vector_l2_ops) WITH (lists=100);
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - manually adjusted ###
    
    # Drop the table, which also drops its indexes and constraints
    op.execute("DROP TABLE IF EXISTS public.embeddings;")
    
    # We'll leave the 'vector' extension in place, as it's harmless
    # and dropping it could affect other tables if you use it elsewhere.
    
    # ### end Alembic commands ###