"""add new users table

Revision ID: c85ba4afc960
Revises: 4de3dfd809bd
Create Date: 2025-11-23 00:28:21.228614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85ba4afc960'
down_revision: Union[str, Sequence[str], None] = '4de3dfd809bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chats', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_chats_owner_id'), 'chats', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'chats', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # op.drop_index(op.f('embeddings_chat_id_idx'), table_name='embeddings')
    # op.drop_index(op.f('embeddings_chat_source_idx'), table_name='embeddings')
    # op.drop_index(op.f('embeddings_embedding_ivfflat'), table_name='embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # op.create_index(op.f('ix_embeddings_chat_id'), 'embeddings', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_embeddings_chat_id'), table_name='embeddings')
    # op.create_index(op.f('embeddings_embedding_ivfflat'), 'embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # op.create_index(op.f('embeddings_chat_source_idx'), 'embeddings', ['chat_id', 'source_table', 'source_id'], unique=False)
    # op.create_index(op.f('embeddings_chat_id_idx'), 'embeddings', ['chat_id'], unique=False)
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_index(op.f('ix_chats_owner_id'), table_name='chats')
    op.drop_column('chats', 'owner_id')
    op.drop_table('users')
    # ### end Alembic commands ###
