"""rename metadata column on embeddings table

Revision ID: e817f10d0cc8
Revises: c4f1502f712e
Create Date: 2025-11-12 11:55:54.052188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e817f10d0cc8'
down_revision: Union[str, Sequence[str], None] = 'c4f1502f712e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('chunk_metadata', sa.JSON(), nullable=True))
    op.alter_column('embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    
    op.drop_column('embeddings', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    
    op.alter_column('embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('embeddings', 'chunk_metadata')
    # ### end Alembic commands ###
