"""Version 6

Revision ID: f8746e269698
Revises: 51088f15a504
Create Date: 2025-10-12 20:42:52.982015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8746e269698'
down_revision: Union[str, Sequence[str], None] = '51088f15a504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_sentiments', sa.Column('overall_label_score', sa.Float(), nullable=False))
    op.alter_column('message_sentiments', 'score_positive',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('message_sentiments', 'score_negative',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('message_sentiments', 'score_neutral',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('segment_sentiments', sa.Column('overall_label_score', sa.Float(), nullable=False))
    op.alter_column('segment_sentiments', 'score_positive',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('segment_sentiments', 'score_negative',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('segment_sentiments', 'score_neutral',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('segment_sentiments', 'score_neutral',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('segment_sentiments', 'score_negative',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('segment_sentiments', 'score_positive',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('segment_sentiments', 'overall_label_score')
    op.alter_column('message_sentiments', 'score_neutral',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('message_sentiments', 'score_negative',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('message_sentiments', 'score_positive',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('message_sentiments', 'overall_label_score')
    # ### end Alembic commands ###
